### ISSUE TITLE
Is there any chance to not kill container when ppp die?

### ISSUE THREAD

**Issue by ghost** [jantman/docker-twilio-ppp-proxy#1]
Sometimes I lost the connection and I don't want to restart the container. 
Because for example on wvdial when connection lost, it reconnect automatically. So is that possible with this container? Not restart but auto reconnect?

**Comment by jantman** [comment]
@ozican That is not possible with this image, at least not without changing it and building it yourself.

The recommended method of use is to run the image with ``docker run --restart always`` to automatically restart the container if the connection is lost.

This container does not use ``wvdial``, it uses ``ppp`` via the ``pon`` script. In my testing, automatic reconnects did not work without restarting the container.
